[ci] Include range of commits in update contrib PRs (#45134)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

This PR adds support to include the range of the commits in the
`update-otel` workflows PRs description.

Also, improved CI actions linting.

```sh
.github/workflows/update-otel.yaml:27:9: shellcheck reported issue in this script: SC2129:style:11:1: Consider using { cmd1; cmd2; } >> file instead of individual redirects [shellcheck]
   |
27 |         run: |
   |         ^~~~
make: *** [Makefile:685: actionlint] Error 1
Error: Process completed with exit code 2.
```

<!-- Issue number (e.g. #1234) or full URL to issue, if applicable. -->
#### Link to tracking issue
Fixes #42519

---------

Signed-off-by: Paulo Dias <paulodias.gm@gmail.com>