[chore][pkg/translator/skywalking] improve linting (#44896)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

This is part of the process to enable the
[modernize](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44199)
linter in CI and upgrade `golanglint` to the latest version.

There are no changes in the component behaviour.

```sh
Error: pkg/translator/skywalking/skywalkingproto_to_traces.go:314:6: G602: slice index out of range (gosec)
		uid[i] ^= byte(extra)
		   ^
Error: pkg/translator/skywalking/skywalkingproto_to_traces.go:355:16: G602: slice index out of range (gosec)
		dst[i] = uuid[i] ^ uuid[i+8]
		             ^
Error: pkg/translator/skywalking/skywalkingproto_to_traces_test.go:300:28: G602: slice index out of range (gosec)
	assert.NotEqual(t, results[0], results[1])
	                          ^
make[2]: *** [../../../Makefile.Common:282: lint] Error 1
make[1]: *** [Makefile:276: pkg/translator/skywalking] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Signed-off-by: Paulo Dias <paulodias.gm@gmail.com>